#!/bin/sh
#
# Start socats


case "$1" in
  start)
        printf "Starting socats: "
        socat TCP-LISTEN:1430,fork TCP:imaps.tin.it:143 &
        socat TCP-LISTEN:14300,fork TCP:in.alice.it:143 &
        ;;
  stop)
	printf "Stopping socats: "
	killall socat && echo "OK" || echo "FAIL"
	;;
  restart|reload)
	"$0" stop
	sleep 1
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
